// <auto-generated />
using System;
using FluxusManager.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FluxusManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929000811_AddSolicitacoesCadastro")]
    partial class AddSolicitacoesCadastro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FluxusManager.Domain.Entities.AdministradorPlataforma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_administradores_plataforma");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_administradores_plataforma_usuario_id")
                        .HasFilter("excluido = false");

                    b.ToTable("administradores_plataforma", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Convite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AceitoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aceito_em");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_convites");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_convites_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_convites_usuario_id");

                    b.HasIndex("PerfilId", "TenantId")
                        .HasDatabaseName("ix_convites_perfil_id_tenant_id");

                    b.HasIndex("TenantId", "CriadoEm")
                        .HasDatabaseName("ix_convites_tenant_id_criado_em");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_convites_tenant_id_email")
                        .HasFilter("status = 'Pendente' AND excluido = false");

                    b.ToTable("convites", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character(14)")
                        .HasColumnName("cnpj")
                        .IsFixedLength();

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razao_social");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_cnpj")
                        .HasFilter("excluido = false");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Filial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character(14)")
                        .HasColumnName("cnpj")
                        .IsFixedLength();

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_filiais");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_filiais_cnpj")
                        .HasFilter("excluido = false");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_filiais_tenant_id");

                    b.ToTable("filiais", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.HasIndex("UsuarioId", "ExpiraEm")
                        .HasDatabaseName("ix_password_reset_tokens_usuario_id_expira_em");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_perfis");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_perfis_id_tenant_id");

                    b.HasIndex("TenantId", "NomeNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_tenant_id_nome_normalizado")
                        .HasFilter("excluido = false");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.PerfilPermissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_perfil_permissoes");

                    b.HasIndex("PerfilId", "TenantId")
                        .HasDatabaseName("ix_perfil_permissoes_perfil_id_tenant_id");

                    b.HasIndex("TenantId", "PerfilId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_perfil_permissoes_tenant_id_perfil_id_codigo")
                        .HasFilter("excluido = false");

                    b.ToTable("perfil_permissoes", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid?>("SubstituidoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("substituido_por_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_refresh_tokens_empresa_id");

                    b.HasIndex("ExpiraEm")
                        .HasDatabaseName("ix_refresh_tokens_expira_em");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_refresh_tokens_familia_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.SolicitacaoCadastro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcompanhamentoExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acompanhamento_expira_em");

                    b.Property<string>("AcompanhamentoTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("acompanhamento_token_hash");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character(14)")
                        .HasColumnName("cnpj")
                        .IsFixedLength();

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DecididaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decidida_em");

                    b.Property<Guid?>("DecididaPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("decidida_por_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_recusa");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("ObservacaoInterna")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao_interna");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razao_social");

                    b.Property<string>("ResponsavelEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("responsavel_email");

                    b.Property<string>("ResponsavelNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("responsavel_nome");

                    b.Property<string>("ResponsavelTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("responsavel_telefone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("VerificacaoExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verificacao_expira_em");

                    b.Property<string>("VerificacaoTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("verificacao_token_hash");

                    b.Property<DateTime?>("VerificadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verificada_em");

                    b.HasKey("Id")
                        .HasName("pk_solicitacoes_cadastro");

                    b.HasIndex("AcompanhamentoTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitacoes_cadastro_acompanhamento_token_hash");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitacoes_cadastro_cnpj")
                        .HasFilter("status IN ('AguardandoVerificacao', 'PendenteAnalise') AND excluido = false");

                    b.HasIndex("DecididaPorId")
                        .HasDatabaseName("ix_solicitacoes_cadastro_decidida_por_id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_solicitacoes_cadastro_empresa_id");

                    b.HasIndex("ResponsavelEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitacoes_cadastro_responsavel_email")
                        .HasFilter("status IN ('AguardandoVerificacao', 'PendenteAnalise') AND excluido = false");

                    b.HasIndex("VerificacaoTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitacoes_cadastro_verificacao_token_hash");

                    b.HasIndex("Status", "CriadoEm")
                        .HasDatabaseName("ix_solicitacoes_cadastro_status_criado_em");

                    b.ToTable("solicitacoes_cadastro", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.SolicitacaoCadastroEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("ConviteId")
                        .HasColumnType("uuid")
                        .HasColumnName("convite_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<DateTime>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacao_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UltimaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_tentativa_em");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_solicitacoes_cadastro_emails");

                    b.HasIndex("ConviteId")
                        .HasDatabaseName("ix_solicitacoes_cadastro_emails_convite_id");

                    b.HasIndex("SolicitacaoId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitacoes_cadastro_emails_solicitacao_id_tipo")
                        .HasFilter("excluido = false");

                    b.HasIndex("Status", "ProximaTentativaEm")
                        .HasDatabaseName("ix_solicitacoes_cadastro_emails_status_proxima_tentativa_em");

                    b.ToTable("solicitacoes_cadastro_emails", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.SolicitacaoCadastroEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacao_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_solicitacoes_cadastro_eventos");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_solicitacoes_cadastro_eventos_usuario_id");

                    b.HasIndex("SolicitacaoId", "CriadoEm")
                        .HasDatabaseName("ix_solicitacoes_cadastro_eventos_solicitacao_id_criado_em");

                    b.ToTable("solicitacoes_cadastro_eventos", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<int>("TentativasLoginFalhas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_login_falhas");

                    b.Property<DateTime?>("UltimaFalhaLoginEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_falha_login_em");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email")
                        .HasFilter("excluido = false");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios_empresas");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_usuarios_empresas_empresa_id");

                    b.HasIndex("PerfilId", "EmpresaId")
                        .HasDatabaseName("ix_usuarios_empresas_perfil_id_empresa_id");

                    b.HasIndex("UsuarioId", "EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_empresas_usuario_id_empresa_id")
                        .HasFilter("excluido = false");

                    b.ToTable("usuarios_empresas", (string)null);
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.AdministradorPlataforma", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_administradores_plataforma_usuario_usuario_id");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Convite", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_convites_empresa_tenant_id");

                    b.HasOne("FluxusManager.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_convites_usuario_usuario_id");

                    b.HasOne("FluxusManager.Domain.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_convites_perfil_perfil_id_tenant_id");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Filial", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_filiais_empresas_tenant_id");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_usuario_usuario_id");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Perfil", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Empresa", null)
                        .WithMany("Perfis")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_perfis_empresas_tenant_id");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_perfil_permissoes_perfis_perfil_id_tenant_id");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_empresas_empresa_id");

                    b.HasOne("FluxusManager.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuario_usuario_id");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.SolicitacaoCadastro", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DecididaPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_solicitacoes_cadastro_usuario_decidida_por_id");

                    b.HasOne("FluxusManager.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_solicitacoes_cadastro_empresas_empresa_id");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.SolicitacaoCadastroEmail", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Convite", null)
                        .WithMany()
                        .HasForeignKey("ConviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_solicitacoes_cadastro_emails_convites_convite_id");

                    b.HasOne("FluxusManager.Domain.Entities.SolicitacaoCadastro", null)
                        .WithMany("Emails")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitacoes_cadastro_emails_solicitacoes_cadastro_solicita");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.SolicitacaoCadastroEvento", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.SolicitacaoCadastro", null)
                        .WithMany("Eventos")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitacoes_cadastro_eventos_solicitacoes_cadastro_solicit");

                    b.HasOne("FluxusManager.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_solicitacoes_cadastro_eventos_usuario_usuario_id");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.HasOne("FluxusManager.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_empresas_empresas_empresa_id");

                    b.HasOne("FluxusManager.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_empresas_usuarios_usuario_id");

                    b.HasOne("FluxusManager.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Vinculos")
                        .HasForeignKey("PerfilId", "EmpresaId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_empresas_perfis_perfil_id_empresa_id");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Perfis");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("Permissoes");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("FluxusManager.Domain.Entities.SolicitacaoCadastro", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
